# Generated by Django 6.0.5 on 2026-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=200),
        ),
    ]
