# Generated by Django 6.0.5 on 2026-09-12 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('special', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='special.genre'),
        ),
        migrations.AddField(
            model_name='novels',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='sections', to='special.sectionname'),
        ),
        migrations.AddField(
            model_name='novels',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='special.tags'),
        ),
        migrations.AddField(
            model_name='comment',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.novels'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.novels'),
        ),
        migrations.AddField(
            model_name='rating',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_log', to='content.novels'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('novel', 'chapter_num'), name='unique_chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'novel')},
        ),
    ]
